# Generated by Django 5.1.7 on 2025-04-10 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('payée', 'Payée'), ('non_payée', 'Non payée')], default='non_payée', max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commande')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.paiement')),
            ],
        ),
    ]
