# Generated by Django 5.1.7 on 2025-04-10 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='categorie_produit',
            field=models.CharField(default='Non défini', max_length=255),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='prix_contrat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
