# Generated by Django 5.1.7 on 2025-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('Carte', 'Carte Bancaire'), ('Mobile Money', 'Mobile Money')], default='espece', max_length=20),
        ),
    ]
